# -*- coding: utf-8 -*-
"""StockPricePredictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jmCnFY5Pz-sc8qLtSzir2C-Hmht0ZpVl
"""

# Description: This program predicts if the stock price of a company will increase or decrease based on top news headlines.

# Valence Away Dictionary for Sentiment Reasoning is an NLTK module that provides sentiment scores based on the words used.
!pip install vaderSentiment

# Import the libraries
import pandas as pd
import numpy as np
from textblob import TextBlob # processing textual data
import re
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

# Load the dtaa
from google.colab import files
files.upload()

# Store the data into variables
df2 = pd.read_csv('p.csv')
df1 = pd.read_csv('Stock Headlines.csv', encoding='ISO-8859-1')
df1['Date'] = pd.to_datetime(df1['Date'], format='%Y-%m-%d').dt.strftime('%m/%d/%Y')
df2['Open'] = df2['Open'].replace({',': ''}, regex = True).astype(float)
df2['High'] = df2['High'].replace({',': ''}, regex = True).astype(float)
df2['Low'] = df2['Low'].replace({',': ''}, regex = True).astype(float)
df2['Close'] = df2['Close'].replace({',': ''}, regex = True).astype(float)

# Show the first 3 rows of the data
df1.head(3)

# Get the number of rows and columns
df1.shape

# Print the first 3 rows of data df2
df2.head(3)

# Get the number of rows and column
df2.shape

# Merge the dataset on the date field
merge = df1.merge(df2, how = 'inner', on = 'Date')

# Show the merge data set
merge

# Combine the top news headlines
headlines = []

for row in range(0, len(merge.index)):
  headlines.append(' '.join(str(x) for x in merge.iloc[row, 2: 27]))

# Print a sample of the combined headlines
headlines[0]

# Add the headlines to merge data
merge['Combined_News'] = headlines

# Show the new column
merge['Combined_News'][0]

# Show the first 3 rows of the merge data
merge.head(3)

# Create function to get the subjectivity
def getSubjectivity(text):
  # TextBlob provides simple APIs for diving into common NLP tasks
  # sentiment properties from TextBlob object
  # subjectivities score from the sentiment properties
  return TextBlob(text).sentiment.subjectivity


# Create function to get the polarity
def getPolarity(text):
  # Measure the positive/negativity of the text
  # Helps determine the overall sentiment of posts content
  return TextBlob(text).sentiment.polarity

# Create two new columns 'Subjectivity and Polarity'
merge['Subjectivity'] = merge['Combined_News'].apply(getSubjectivity)
merge['Polarity'] = merge['Combined_News'].apply(getPolarity)

"""Polarity: Measures the positive or negativity of news articles, tweets, or report about the stock. Range - 1 to 1. -1: mean very negative. 0: neutral sentiment. 1: very positive
Subjectivity: Gauges the amount of personal opinion or factual information in text. 0: very objective (factual). 1: very subjective (personal)
"""

# Show the new columns in the merge data
merge.head(3)

# Create a function to get the sentiment scores
def getSIA(text):
  # pre trianed to recognize sentiment laden words and phrases
  sia = SentimentIntensityAnalyzer()
  # calculate sentiment scores for the input text and return:
  # compound - overall sentiment score (-1 to 1 -> most negative to most positive)
  # neg - proportion of negative sentiment in the text
  # neu
  # pos
  sentiment = sia.polarity_scores(text)
  return sentiment # dictionary containing sentiment score

# Get the sentiment scores for each day
compound = []
neg = []
neu = []
pos = []
SIA = 0

for i in range(0, len(merge['Combined_News'])):
  SIA = getSIA(merge['Combined_News'][i])
  compound.append(SIA['compound'])
  neg.append(SIA['neg'])
  neu.append(SIA['neu'])
  pos.append(SIA['pos'])

# Store the sentiment scores in the merge data set
merge['Compound'] = compound
merge['Negative'] = neg
merge['Neutral'] = neu
merge['Positive'] = pos

merge.head(3)

# Create a list of columns to keep
# Label is stock up or down (0 or 1)
keep_columns = ['Open', 'High', 'Low', 'Subjectivity', 'Polarity', 'Compound', 'Negative', 'Neutral', 'Positive', 'Label']
df = merge[keep_columns]
df

# Create the feature data set
X = df
# dataframe remove the column name label and set the left to array. 1: column, 0: row
X = np.array(X.drop(['Label'], axis = 1))

# Create the target data set
y = np.array(df['Label'])

# Split the data into 80% training and 20% testing data
# train_test_split used to split arrays or matrices into random train and test subsets
# X: feature database(inputs) y: target database(ooutput)
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Create and train the model
model = LinearDiscriminantAnalysis().fit(x_train, y_train)

# Show the models predictions
predictions = model.predict(x_test)
predictions

y_test

# Show the model metrics
print(classification_report(y_test, predictions))

"""precision: accuracy of actual predictions (74% of predicted as 0 were actually class 0)
recall: ability of model to finda all the relevant cases (58% of actual class 0 were correctly identified)
F1-score: precision / recall provide balance between two
"""