# -*- coding: utf-8 -*-
"""StockPricePredictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jmCnFY5Pz-sc8qLtSzir2C-Hmht0ZpVl
"""

# Description: This program predicts if the stock price of a company will increase or decrease based on top news headlines.

# Valence Away Dictionary for Sentiment Reasoning is an NLTK module that provides sentiment scores based on the words used.
!pip install vaderSentiment

# Commented out IPython magic to ensure Python compatibility.
# Install TensorFlow
# !pip install -q tensorflow-gpu==2.0.0-beta1

try:
#   %tensorflow_version 2.x  # Colab only.
except Exception:
  pass

import tensorflow as tf
print(tf.__version__)

# Import the libraries
import pandas as pd
import numpy as np
from textblob import TextBlob # processing textual data
import re
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
# Using SVM (Support Vector Machine) model
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler

from tensorflow.keras.layers import Input, LSTM, GRU, SimpleRNN, Dense, GlobalMaxPool1D
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import SGD, Adam


import matplotlib.pyplot as plt

# Load the dtaa
from google.colab import files
files.upload()

# Store the data into variables
df2 = pd.read_csv('p.csv')
df1 = pd.read_csv('Stock Headlines.csv', encoding='ISO-8859-1')
df1['Date'] = pd.to_datetime(df1['Date'], format='%Y-%m-%d').dt.strftime('%m/%d/%Y')
df2['Open'] = df2['Open'].replace({',': ''}, regex = True).astype(float)
df2['High'] = df2['High'].replace({',': ''}, regex = True).astype(float)
df2['Low'] = df2['Low'].replace({',': ''}, regex = True).astype(float)
df2['Close'] = df2['Close'].replace({',': ''}, regex = True).astype(float)

# Show the first 3 rows of the data
df1.head(3)

# Get the number of rows and columns
df1.shape

# Print the first 3 rows of data df2
df2.head(3)

# Get the number of rows and column
df2.shape

# Merge the dataset on the date field
merge = df1.merge(df2, how = 'inner', on = 'Date')

# Show the merge data set
merge

# Combine the top news headlines
headlines = []

for row in range(0, len(merge.index)):
  headlines.append(' '.join(str(x) for x in merge.iloc[row, 2: 27]))

# Print a sample of the combined headlines
headlines[0]

# Add the headlines to merge data
merge['Combined_News'] = headlines

# Show the new column
merge['Combined_News'][0]

# Show the first 3 rows of the merge data
merge.head(3)

# Create function to get the subjectivity
def getSubjectivity(text):
  # TextBlob provides simple APIs for diving into common NLP tasks
  # sentiment properties from TextBlob object
  # subjectivities score from the sentiment properties
  return TextBlob(text).sentiment.subjectivity


# Create function to get the polarity
def getPolarity(text):
  # Measure the positive/negativity of the text
  # Helps determine the overall sentiment of posts content
  return TextBlob(text).sentiment.polarity

# Create two new columns 'Subjectivity and Polarity'
merge['Subjectivity'] = merge['Combined_News'].apply(getSubjectivity)
merge['Polarity'] = merge['Combined_News'].apply(getPolarity)

"""Polarity: Measures the positive or negativity of news articles, tweets, or report about the stock. Range - 1 to 1. -1: mean very negative. 0: neutral sentiment. 1: very positive
Subjectivity: Gauges the amount of personal opinion or factual information in text. 0: very objective (factual). 1: very subjective (personal)
"""

# Show the new columns in the merge data
merge.head(3)

# Create a function to get the sentiment scores
def getSIA(text):
  # pre trianed to recognize sentiment laden words and phrases
  sia = SentimentIntensityAnalyzer()
  # calculate sentiment scores for the input text and return:
  # compound - overall sentiment score (-1 to 1 -> most negative to most positive)
  # neg - proportion of negative sentiment in the text
  # neu
  # pos
  sentiment = sia.polarity_scores(text)
  return sentiment # dictionary containing sentiment score

# Get the sentiment scores for each day
compound = []
neg = []
neu = []
pos = []
SIA = 0

for i in range(0, len(merge['Combined_News'])):
  SIA = getSIA(merge['Combined_News'][i])
  compound.append(SIA['compound'])
  neg.append(SIA['neg'])
  neu.append(SIA['neu'])
  pos.append(SIA['pos'])

# Store the sentiment scores in the merge data set
merge['Compound'] = compound
merge['Negative'] = neg
merge['Neutral'] = neu
merge['Positive'] = pos

merge.head(3)

# Create a list of columns to keep
# Label is stock up or down (0 or 1)
keep_columns = ['Open', 'High', 'Low', 'Subjectivity', 'Polarity', 'Compound', 'Negative', 'Neutral', 'Positive', 'Label']
df = merge[keep_columns]
df

# Create feature
X = df.drop(['Label'], axis = 1)
# Create target
y = df['Label']

# Feature scaling
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

#split
x_train, x_test, y_train, y_test = train_test_split(X_scaled, y, test_size = 0.2, random_state = 0)

# Train SVM model
svm_model = SVC(kernel = 'rbf', gamma = 'scale', random_state = 0)
svm_model.fit(x_train, y_train)

# Evaluate
predictions = svm_model.predict(x_test)

# Show the classification report
print(classification_report(y_test, predictions))

# Create and train the model
model = LinearDiscriminantAnalysis().fit(x_train, y_train)

# Show the models predictions
predictions = model.predict(x_test)
predictions

# Show the model metrics
print(classification_report(y_test, predictions))

"""It is unconventional to predict stock prices. So I will try the more conventionally way to predict in stock return:
R = (V_final - V_initial) / V_initial
"""

# To calculate the return, first step will be shifting the data
df2['PrevClose'] = df2['Close'].shift(1)

df2.head()

# Then calculate the return here
df2['Return'] = (df2['Close'] - df2['PrevClose']) / df2['PrevClose']

df2.head()

# Draw histogram to see the distribution of return
df2['Return'].hist()

series = df2['Return'].values[1:].reshape(-1,1)

# Normalize the data
# Note: I didn't think about where the true boundary is, this is just approx.
scaler = StandardScaler()
scaler.fit(series[:len(series) // 2])
series = scaler.transform(series).flatten()

### build the dataset
T = 10
D = 1
X = []
Y = []
for t in range(len(series) - T):
  x = series[t:t+T]
  X.append(x)
  y = series[t+T]
  Y.append(y)

X = np.array(X).reshape(-1, T, 1) # Now the data should be N x T x D
Y = np.array(Y)
N = len(X)
print("X.shape", X.shape, "Y.shape", Y.shape)

### try autoregressive RNN model
i = Input(shape=(T, 1))
x = LSTM(5)(i)
x = Dense(1)(x)
model = Model(i, x)
model.compile(
  loss='mse',
  optimizer=Adam(learning_rate=0.01),
)

# train the RNN
r = model.fit(
  X[:-N//2], Y[:-N//2],
  epochs=80,
  validation_data=(X[-N//2:], Y[-N//2:]),
)

# Plot loss per iteration
import matplotlib.pyplot as plt
plt.plot(r.history['loss'], label='loss')
plt.plot(r.history['val_loss'], label='val_loss')
plt.legend()

# One-step forecast using true targets
outputs = model.predict(X)
print(outputs.shape)
predictions = outputs[:,0]

plt.plot(Y, label='targets')
plt.plot(predictions, label='predictions')
plt.legend()
plt.show()

# Multi-step forecast
validation_target = Y[-N//2:]
validation_predictions = []

# first validation input
last_x = X[-N//2] # 1-D array of length T

while len(validation_predictions) < len(validation_target):
  p = model.predict(last_x.reshape(1, T, 1))[0,0] # 1x1 array -> scalar

  # update the predictions list
  validation_predictions.append(p)

  # make the new input
  last_x = np.roll(last_x, -1)
  last_x[-1] = p

plt.plot(validation_target, label='forecast target')
plt.plot(validation_predictions, label='forecast prediction')
plt.legend()

"""Now try to use of all the data: open, high, low, close and predict whether the price will go up or down. REgression is harder than classification."""

# Now turn the full data into numpy arrays

# Not yet in the final "X" format!
input_data = df2[['Open', 'High', 'Low', 'Close']].values
targets = df2['Return'].values

# Now make the actual data which will go into the neural network
T = 10 # the number of time steps to look at to make a prediction for the next day (can try different #)
D = input_data.shape[1]
N = len(input_data) - T # (e.g. if T=10 and you have 11 data points then you'd only have 1 sample)

# normalize the inputs
Ntrain = len(input_data) * 2 // 3
scaler = StandardScaler()
scaler.fit(input_data[:Ntrain + T - 1])
input_data = scaler.transform(input_data)

# Setup X_train and Y_train
X_train = np.zeros((Ntrain, T, D))
Y_train = np.zeros(Ntrain)

for t in range(Ntrain):
  X_train[t, :, :] = input_data[t:t+T]
  Y_train[t] = (targets[t+T] > 0)

# Setup X_test and Y_test
X_test = np.zeros((N - Ntrain, T, D))
Y_test = np.zeros(N - Ntrain)

for u in range(N - Ntrain):
  # u counts from 0...(N - Ntrain)
  # t counts from Ntrain...N
  t = u + Ntrain
  X_test[u, :, :] = input_data[t:t+T]
  Y_test[u] = (targets[t+T] > 0)

# make the RNN
i = Input(shape=(T, D))
x = LSTM(50)(i)
x = Dense(1, activation='sigmoid')(x)
model = Model(i, x)
model.compile(
  loss='binary_crossentropy',
  optimizer=Adam(learning_rate=0.001),
  metrics=['accuracy'],
)

# train the RNN
r = model.fit(
  X_train, Y_train,
  batch_size=32,
  epochs=300,
  validation_data=(X_test, Y_test),
)

# plot the loss
plt.plot(r.history['loss'], label='loss')
plt.plot(r.history['val_loss'], label='val_loss')
plt.legend()
plt.show()

# Plot accuracy per iteration
# in binary classification, the worse accuarcy is 50%
plt.plot(r.history['accuracy'], label='accuracy')
plt.plot(r.history['val_accuracy'], label='val_accuracy')
plt.legend()
plt.show()

"""Predict orices from past stick prices with LSTM. It only appears to work weel as we will see the model will keep copying the previous data.
Predict future stock returns is okay.
The best is using all columns for binary classification for stock price up or down.
"""